### PR TITLE
update package ref for graphql to graphql-cli

### PR DESCRIPTION
**Pull request by mikaelkaron**
the command `graphql` is provided by the [`graphql-cli`](https://github.com/graphql-cli/graphql-cli) package - updated docs

### CODE REVIEW

**Comment by nikolasburk** [comment]
Thanks a lot for this @mikaelkaron 🙌

**Comment by nikolasburk** [comment]
Ah, sorry! Actually I just realized that the code was correct... we need to install the `graphql` package (which contains the GraphQL.js reference implementation) explicitly when using `prisma-binding`. The  GraphQL CLI can of course be installed separately, but that's not what we need here. 
Still, thanks a lot for creating this PR. Please feel free to open more PRs in the future!

**Comment by nikolasburk** [comment]
> install `graphql-cli` to execute `npx graphql get-schema`

Hmm, actually the point of using `npx` here is that you don't have to install the `graphql-cli` but still can use it by prefixing it with `npx`. Did that not work for you? Did `npx graphql get-schema` fail?

**Comment by mikaelkaron** [comment]
```cmd
npx graphql
npx: installed 2 in 5.373s
command not found: graphql
```

```
npx graphql-cli
npx: installed 448 in 65.314s
Usage: graphql [command]
...
```

**Pull request merged**
